name = "jaat-captain-panel"
compatibility_date = "2026-08-26"
pages_build_output_dir = "."
[[d1_databases]]
binding = "DB"
database_name = "sergio-keys"
database_id = "fd898fe9-e8d2-4d90-8079-50c359823bd9"
